remote_theme: mmistakes/minimal-mistakes

# Build settings
plugins:
  - jekyll-include-cache

title: "Abhishek Seth"
name: "Abhishek Seth"
description: "Doctoral Student in Economics at IIT Roorkee. Research interests include corporate finance, taxation, financial distress, and municipal finance."

url: "https://abhishekseth98.github.io"

author:
  name: "Abhishek Seth"
logo: ""

# Navigation
nav:
  - title: "Home"
    url: /
  - title: "Education"
    url: /education/
  - title: "Research"
    url: /research/
  - title: "Teaching"
    url: /teaching/
  - title: "CV"
    url: /cv/

# Minimal Mistakes theme font
fonts:
  heading:
    family: "Merriweather"
  body:
    family: "Lora"
